# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from delphi.proto import diamond_pb2 as proto_dot_diamond__pb2


class DiamondServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FilterInit = channel.unary_unary(
                '/DiamondService/FilterInit',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
                response_deserializer=proto_dot_diamond__pb2.FilterRole.FromString,
                )


class DiamondServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def FilterInit(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiamondServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FilterInit': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterInit,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                    response_serializer=proto_dot_diamond__pb2.FilterRole.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DiamondService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiamondService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def FilterInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DiamondService/FilterInit',
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            proto_dot_diamond__pb2.FilterRole.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
