# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/diamond.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/diamond.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13proto/diamond.proto\x1a\x1egoogle/protobuf/wrappers.proto\"9\n\nFilterRole\x12\x14\n\x0csendExamples\x18\x01 \x01(\x08\x12\x15\n\rrequestExport\x18\x02 \x01(\x08\x32G\n\x0e\x44iamondService\x12\x35\n\nFilterInit\x12\x1a.google.protobuf.BoolValue\x1a\x0b.FilterRoleb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_FILTERROLE = _descriptor.Descriptor(
  name='FilterRole',
  full_name='FilterRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendExamples', full_name='FilterRole.sendExamples', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestExport', full_name='FilterRole.requestExport', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['FilterRole'] = _FILTERROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterRole = _reflection.GeneratedProtocolMessageType('FilterRole', (_message.Message,), {
  'DESCRIPTOR' : _FILTERROLE,
  '__module__' : 'proto.diamond_pb2'
  # @@protoc_insertion_point(class_scope:FilterRole)
  })
_sym_db.RegisterMessage(FilterRole)



_DIAMONDSERVICE = _descriptor.ServiceDescriptor(
  name='DiamondService',
  full_name='DiamondService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=114,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='FilterInit',
    full_name='DiamondService.FilterInit',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    output_type=_FILTERROLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIAMONDSERVICE)

DESCRIPTOR.services_by_name['DiamondService'] = _DIAMONDSERVICE

# @@protoc_insertion_point(module_scope)
