# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/internal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from delphi.proto import learning_module_pb2 as proto_dot_learning__module__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/internal.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14proto/internal.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bproto/learning_module.proto\"H\n\x12GetExamplesRequest\x12\x1f\n\nexampleSet\x18\x01 \x01(\x0e\x32\x0b.ExampleSet\x12\x11\n\tnodeIndex\x18\x02 \x01(\x05\"-\n\x0f\x45xampleMetadata\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"P\n\x11GetExampleRequest\x12\x1f\n\nexampleSet\x18\x01 \x01(\x0e\x32\x0b.ExampleSet\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"K\n\x11StageModelRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x14\n\x0ctrainerIndex\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\";\n\nTestResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"N\n\x0fInternalMessage\x12\x14\n\x0ctrainerIndex\x18\x01 \x01(\x05\x12%\n\x07message\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any2\xcd\x04\n\x0fInternalService\x12\x36\n\x0bGetExamples\x12\x13.GetExamplesRequest\x1a\x10.ExampleMetadata0\x01\x12=\n\nGetExample\x12\x12.GetExampleRequest\x1a\x1b.google.protobuf.BytesValue\x12<\n\x05Train\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Empty\x12\x38\n\nStageModel\x12\x12.StageModelRequest\x1a\x16.google.protobuf.Empty\x12J\n\x13ValidateTestResults\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Empty\x12:\n\x11SubmitTestResults\x12\x0b.TestResult\x1a\x16.google.protobuf.Empty(\x01\x12\x43\n\x0cPromoteModel\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Empty\x12\x43\n\x0c\x44iscardModel\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Empty\x12\x39\n\x0fMessageInternal\x12\x10.InternalMessage\x1a\x14.google.protobuf.Anyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,proto_dot_learning__module__pb2.DESCRIPTOR,])




_GETEXAMPLESREQUEST = _descriptor.Descriptor(
  name='GetExamplesRequest',
  full_name='GetExamplesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exampleSet', full_name='GetExamplesRequest.exampleSet', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeIndex', full_name='GetExamplesRequest.nodeIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=213,
)


_EXAMPLEMETADATA = _descriptor.Descriptor(
  name='ExampleMetadata',
  full_name='ExampleMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ExampleMetadata.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='ExampleMetadata.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=260,
)


_GETEXAMPLEREQUEST = _descriptor.Descriptor(
  name='GetExampleRequest',
  full_name='GetExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exampleSet', full_name='GetExampleRequest.exampleSet', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='GetExampleRequest.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='GetExampleRequest.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=342,
)


_STAGEMODELREQUEST = _descriptor.Descriptor(
  name='StageModelRequest',
  full_name='StageModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='StageModelRequest.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trainerIndex', full_name='StageModelRequest.trainerIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='StageModelRequest.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=419,
)


_TESTRESULT = _descriptor.Descriptor(
  name='TestResult',
  full_name='TestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='TestResult.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='TestResult.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='TestResult.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=480,
)


_INTERNALMESSAGE = _descriptor.Descriptor(
  name='InternalMessage',
  full_name='InternalMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainerIndex', full_name='InternalMessage.trainerIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='InternalMessage.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=560,
)

_GETEXAMPLESREQUEST.fields_by_name['exampleSet'].enum_type = proto_dot_learning__module__pb2._EXAMPLESET
_GETEXAMPLEREQUEST.fields_by_name['exampleSet'].enum_type = proto_dot_learning__module__pb2._EXAMPLESET
_INTERNALMESSAGE.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['GetExamplesRequest'] = _GETEXAMPLESREQUEST
DESCRIPTOR.message_types_by_name['ExampleMetadata'] = _EXAMPLEMETADATA
DESCRIPTOR.message_types_by_name['GetExampleRequest'] = _GETEXAMPLEREQUEST
DESCRIPTOR.message_types_by_name['StageModelRequest'] = _STAGEMODELREQUEST
DESCRIPTOR.message_types_by_name['TestResult'] = _TESTRESULT
DESCRIPTOR.message_types_by_name['InternalMessage'] = _INTERNALMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetExamplesRequest = _reflection.GeneratedProtocolMessageType('GetExamplesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEXAMPLESREQUEST,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:GetExamplesRequest)
  })
_sym_db.RegisterMessage(GetExamplesRequest)

ExampleMetadata = _reflection.GeneratedProtocolMessageType('ExampleMetadata', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEMETADATA,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:ExampleMetadata)
  })
_sym_db.RegisterMessage(ExampleMetadata)

GetExampleRequest = _reflection.GeneratedProtocolMessageType('GetExampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEXAMPLEREQUEST,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:GetExampleRequest)
  })
_sym_db.RegisterMessage(GetExampleRequest)

StageModelRequest = _reflection.GeneratedProtocolMessageType('StageModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _STAGEMODELREQUEST,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:StageModelRequest)
  })
_sym_db.RegisterMessage(StageModelRequest)

TestResult = _reflection.GeneratedProtocolMessageType('TestResult', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESULT,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:TestResult)
  })
_sym_db.RegisterMessage(TestResult)

InternalMessage = _reflection.GeneratedProtocolMessageType('InternalMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALMESSAGE,
  '__module__' : 'proto.internal_pb2'
  # @@protoc_insertion_point(class_scope:InternalMessage)
  })
_sym_db.RegisterMessage(InternalMessage)



_INTERNALSERVICE = _descriptor.ServiceDescriptor(
  name='InternalService',
  full_name='InternalService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=563,
  serialized_end=1152,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetExamples',
    full_name='InternalService.GetExamples',
    index=0,
    containing_service=None,
    input_type=_GETEXAMPLESREQUEST,
    output_type=_EXAMPLEMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetExample',
    full_name='InternalService.GetExample',
    index=1,
    containing_service=None,
    input_type=_GETEXAMPLEREQUEST,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BYTESVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='InternalService.Train',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StageModel',
    full_name='InternalService.StageModel',
    index=3,
    containing_service=None,
    input_type=_STAGEMODELREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ValidateTestResults',
    full_name='InternalService.ValidateTestResults',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitTestResults',
    full_name='InternalService.SubmitTestResults',
    index=5,
    containing_service=None,
    input_type=_TESTRESULT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PromoteModel',
    full_name='InternalService.PromoteModel',
    index=6,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DiscardModel',
    full_name='InternalService.DiscardModel',
    index=7,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MessageInternal',
    full_name='InternalService.MessageInternal',
    index=8,
    containing_service=None,
    input_type=_INTERNALMESSAGE,
    output_type=google_dot_protobuf_dot_any__pb2._ANY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERNALSERVICE)

DESCRIPTOR.services_by_name['InternalService'] = _INTERNALSERVICE

# @@protoc_insertion_point(module_scope)
