# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.learning_module_pb2 import (
    ExampleSet as proto___learning_module_pb2___ExampleSet,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class GetExamplesRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    exampleSet = ... # type: proto___learning_module_pb2___ExampleSet
    nodeIndex = ... # type: builtin___int

    def __init__(self,
        *,
        exampleSet : typing___Optional[proto___learning_module_pb2___ExampleSet] = None,
        nodeIndex : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetExamplesRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetExamplesRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"exampleSet",b"exampleSet",u"nodeIndex",b"nodeIndex"]) -> None: ...
global___GetExamplesRequest = GetExamplesRequest

class ExampleMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    label = ... # type: typing___Text
    key = ... # type: typing___Text

    def __init__(self,
        *,
        label : typing___Optional[typing___Text] = None,
        key : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExampleMetadata: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ExampleMetadata: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"label",b"label"]) -> None: ...
global___ExampleMetadata = ExampleMetadata

class GetExampleRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    exampleSet = ... # type: proto___learning_module_pb2___ExampleSet
    label = ... # type: typing___Text
    key = ... # type: typing___Text

    def __init__(self,
        *,
        exampleSet : typing___Optional[proto___learning_module_pb2___ExampleSet] = None,
        label : typing___Optional[typing___Text] = None,
        key : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetExampleRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetExampleRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"exampleSet",b"exampleSet",u"key",b"key",u"label",b"label"]) -> None: ...
global___GetExampleRequest = GetExampleRequest

class StageModelRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    trainerIndex = ... # type: builtin___int
    content = ... # type: builtin___bytes

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        trainerIndex : typing___Optional[builtin___int] = None,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> StageModelRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> StageModelRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"trainerIndex",b"trainerIndex",u"version",b"version"]) -> None: ...
global___StageModelRequest = StageModelRequest

class TestResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    label = ... # type: typing___Text
    score = ... # type: builtin___float

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        label : typing___Optional[typing___Text] = None,
        score : typing___Optional[builtin___float] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TestResult: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> TestResult: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"label",b"label",u"score",b"score",u"version",b"version"]) -> None: ...
global___TestResult = TestResult

class InternalMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    trainerIndex = ... # type: builtin___int

    @property
    def message(self) -> google___protobuf___any_pb2___Any: ...

    def __init__(self,
        *,
        trainerIndex : typing___Optional[builtin___int] = None,
        message : typing___Optional[google___protobuf___any_pb2___Any] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> InternalMessage: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> InternalMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"message",b"message"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"message",b"message",u"trainerIndex",b"trainerIndex"]) -> None: ...
global___InternalMessage = InternalMessage
