# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class ExampleSet(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'ExampleSet': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['ExampleSet']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ExampleSet']]: ...
    TRAIN = typing___cast('ExampleSet', 0)
    TEST = typing___cast('ExampleSet', 1)
TRAIN = typing___cast('ExampleSet', 0)
TEST = typing___cast('ExampleSet', 1)
global___ExampleSet = ExampleSet

class InferRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    objectId = ... # type: typing___Text
    content = ... # type: builtin___bytes

    def __init__(self,
        *,
        objectId : typing___Optional[typing___Text] = None,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> InferRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> InferRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"objectId",b"objectId"]) -> None: ...
global___InferRequest = InferRequest

class InferResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    objectId = ... # type: typing___Text
    label = ... # type: typing___Text
    score = ... # type: builtin___float
    modelVersion = ... # type: builtin___int

    def __init__(self,
        *,
        objectId : typing___Optional[typing___Text] = None,
        label : typing___Optional[typing___Text] = None,
        score : typing___Optional[builtin___float] = None,
        modelVersion : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> InferResult: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> InferResult: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"label",b"label",u"modelVersion",b"modelVersion",u"objectId",b"objectId",u"score",b"score"]) -> None: ...
global___InferResult = InferResult

class LabeledExample(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    label = ... # type: typing___Text
    content = ... # type: builtin___bytes

    @property
    def exampleSet(self) -> global___ExampleSetWrapper: ...

    def __init__(self,
        *,
        label : typing___Optional[typing___Text] = None,
        content : typing___Optional[builtin___bytes] = None,
        exampleSet : typing___Optional[global___ExampleSetWrapper] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> LabeledExample: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> LabeledExample: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"exampleSet",b"exampleSet"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"exampleSet",b"exampleSet",u"label",b"label"]) -> None: ...
global___LabeledExample = LabeledExample

class ExampleSetWrapper(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    value = ... # type: global___ExampleSet

    def __init__(self,
        *,
        value : typing___Optional[global___ExampleSet] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExampleSetWrapper: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ExampleSetWrapper: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> None: ...
global___ExampleSetWrapper = ExampleSetWrapper

class ModelStatistics(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    testExamples = ... # type: builtin___int
    auc = ... # type: builtin___float
    bestThreshold = ... # type: builtin___float
    precisions = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float]
    recalls = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float]
    thresholds = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float]
    version = ... # type: builtin___int

    @property
    def validationMetrics(self) -> global___ModelMetrics: ...

    @property
    def idealMetrics(self) -> global___ModelMetrics: ...

    def __init__(self,
        *,
        testExamples : typing___Optional[builtin___int] = None,
        auc : typing___Optional[builtin___float] = None,
        validationMetrics : typing___Optional[global___ModelMetrics] = None,
        idealMetrics : typing___Optional[global___ModelMetrics] = None,
        bestThreshold : typing___Optional[builtin___float] = None,
        precisions : typing___Optional[typing___Iterable[builtin___float]] = None,
        recalls : typing___Optional[typing___Iterable[builtin___float]] = None,
        thresholds : typing___Optional[typing___Iterable[builtin___float]] = None,
        version : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ModelStatistics: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ModelStatistics: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"idealMetrics",b"idealMetrics",u"validationMetrics",b"validationMetrics"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"auc",b"auc",u"bestThreshold",b"bestThreshold",u"idealMetrics",b"idealMetrics",u"precisions",b"precisions",u"recalls",b"recalls",u"testExamples",b"testExamples",u"thresholds",b"thresholds",u"validationMetrics",b"validationMetrics",u"version",b"version"]) -> None: ...
global___ModelStatistics = ModelStatistics

class ModelMetrics(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    truePositives = ... # type: builtin___int
    falsePositives = ... # type: builtin___int
    falseNegatives = ... # type: builtin___int
    precision = ... # type: builtin___float
    recall = ... # type: builtin___float
    f1Score = ... # type: builtin___float

    def __init__(self,
        *,
        truePositives : typing___Optional[builtin___int] = None,
        falsePositives : typing___Optional[builtin___int] = None,
        falseNegatives : typing___Optional[builtin___int] = None,
        precision : typing___Optional[builtin___float] = None,
        recall : typing___Optional[builtin___float] = None,
        f1Score : typing___Optional[builtin___float] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ModelMetrics: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ModelMetrics: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"f1Score",b"f1Score",u"falseNegatives",b"falseNegatives",u"falsePositives",b"falsePositives",u"precision",b"precision",u"recall",b"recall",u"truePositives",b"truePositives"]) -> None: ...
global___ModelMetrics = ModelMetrics

class ImportModelRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    content = ... # type: builtin___bytes

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ImportModelRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ImportModelRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"version",b"version"]) -> None: ...
global___ImportModelRequest = ImportModelRequest

class ModelArchive(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version = ... # type: builtin___int
    content = ... # type: builtin___bytes

    def __init__(self,
        *,
        version : typing___Optional[builtin___int] = None,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ModelArchive: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ModelArchive: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"version",b"version"]) -> None: ...
global___ModelArchive = ModelArchive
