# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/svm_trainer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/svm_trainer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17proto/svm_trainer.proto\"n\n\x11SVMTrainerMessage\x12)\n\x0esetTrainResult\x18\x01 \x01(\x0b\x32\x0f.SetTrainResultH\x00\x12%\n\x0csetParamGrid\x18\x02 \x01(\x0b\x32\r.SetParamGridH\x00\x42\x07\n\x05value\"O\n\x0eSetTrainResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06params\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\x0c\"\x1c\n\x0cSetParamGrid\x12\x0c\n\x04grid\x18\x01 \x01(\tb\x06proto3'
)




_SVMTRAINERMESSAGE = _descriptor.Descriptor(
  name='SVMTrainerMessage',
  full_name='SVMTrainerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setTrainResult', full_name='SVMTrainerMessage.setTrainResult', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setParamGrid', full_name='SVMTrainerMessage.setParamGrid', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='SVMTrainerMessage.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=27,
  serialized_end=137,
)


_SETTRAINRESULT = _descriptor.Descriptor(
  name='SetTrainResult',
  full_name='SetTrainResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='SetTrainResult.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='SetTrainResult.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='SetTrainResult.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='SetTrainResult.model', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=218,
)


_SETPARAMGRID = _descriptor.Descriptor(
  name='SetParamGrid',
  full_name='SetParamGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grid', full_name='SetParamGrid.grid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=248,
)

_SVMTRAINERMESSAGE.fields_by_name['setTrainResult'].message_type = _SETTRAINRESULT
_SVMTRAINERMESSAGE.fields_by_name['setParamGrid'].message_type = _SETPARAMGRID
_SVMTRAINERMESSAGE.oneofs_by_name['value'].fields.append(
  _SVMTRAINERMESSAGE.fields_by_name['setTrainResult'])
_SVMTRAINERMESSAGE.fields_by_name['setTrainResult'].containing_oneof = _SVMTRAINERMESSAGE.oneofs_by_name['value']
_SVMTRAINERMESSAGE.oneofs_by_name['value'].fields.append(
  _SVMTRAINERMESSAGE.fields_by_name['setParamGrid'])
_SVMTRAINERMESSAGE.fields_by_name['setParamGrid'].containing_oneof = _SVMTRAINERMESSAGE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['SVMTrainerMessage'] = _SVMTRAINERMESSAGE
DESCRIPTOR.message_types_by_name['SetTrainResult'] = _SETTRAINRESULT
DESCRIPTOR.message_types_by_name['SetParamGrid'] = _SETPARAMGRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SVMTrainerMessage = _reflection.GeneratedProtocolMessageType('SVMTrainerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SVMTRAINERMESSAGE,
  '__module__' : 'proto.svm_trainer_pb2'
  # @@protoc_insertion_point(class_scope:SVMTrainerMessage)
  })
_sym_db.RegisterMessage(SVMTrainerMessage)

SetTrainResult = _reflection.GeneratedProtocolMessageType('SetTrainResult', (_message.Message,), {
  'DESCRIPTOR' : _SETTRAINRESULT,
  '__module__' : 'proto.svm_trainer_pb2'
  # @@protoc_insertion_point(class_scope:SetTrainResult)
  })
_sym_db.RegisterMessage(SetTrainResult)

SetParamGrid = _reflection.GeneratedProtocolMessageType('SetParamGrid', (_message.Message,), {
  'DESCRIPTOR' : _SETPARAMGRID,
  '__module__' : 'proto.svm_trainer_pb2'
  # @@protoc_insertion_point(class_scope:SetParamGrid)
  })
_sym_db.RegisterMessage(SetParamGrid)


# @@protoc_insertion_point(module_scope)
